install:
  - ps: Start-FileDownload 'http://neo4j.com/artifact.php?name=neo4j-community-2.3.2-windows.zip' -FileName "$env:APPVEYOR_BUILD_FOLDER\neo4j-community-2.3.2-windows.zip"
  - cmd: 7z x %APPVEYOR_BUILD_FOLDER%\neo4j-community-2.3.2-windows.zip
  - ps: .\setup-neo4j.ps1
version: 0.9.{build}
pull_requests:
  do_not_increment_build_number: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build:
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: UFKXWUd+DCrlU6Nd5vL2561QhzK/fqcroXixaOCMBdMzT1fWwhouWwmcGnZSPiyK
  skip_symbols: true
  on:
    branch: master
